/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ape2je;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class EditCapacity extends javax.swing.JFrame {
    PreparedStatement ps = null;
    ResultSet rs = null;
    PreparedStatement ps2 = null;
    PreparedStatement ps3 = null;
    Connection con = ConnectDatabase.connectdb();
    LecturerViewModules lvm = new LecturerViewModules();
    String mod = lvm.getMod();
    String cap = lvm.getCap();
    String act = lvm.getAct();
    String occ = lvm.getOccu();
    /**
     * Creates new form EditCapacity
     */
    public EditCapacity() {
        ConnectDatabase.connectdb();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NewCapacity = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        NewCapacity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewCapacityActionPerformed(evt);
            }
        });

        jLabel1.setText("WHAT CAPACITY?");

        jButton1.setText("EDIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(NewCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(NewCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NewCapacityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewCapacityActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_NewCapacityActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String newcap = NewCapacity.getText();
        String q1 = "SELECT * FROM VALIDMODULES2 WHERE MODULES = '" + mod + "' AND OCCURENCE = " + occ + "ORDER BY OCCURENCE";
        String ACTIVITYTYPE = "";
        String LECTURER = "";
        String DAY = "";
        String START = "";
        String END = "";
        String CAP ="";
        if(Integer.parseInt(act)>Integer.parseInt(newcap)){
                JOptionPane.showMessageDialog(null, "The capacity is less than the registered student. Please insert a higher number.");
            }
        else{
        try {
            ps = con.prepareStatement(q1);
            rs = ps.executeQuery();
            while (rs.next()) {
                DAY = rs.getString("DAY");
                START = rs.getString("TIMESTART");
                END = rs.getString("TIMEEND");
                ACTIVITYTYPE = rs.getString("ACTIVITYTYPE");
                LECTURER = rs.getString("LECTURER");
                CAP = rs.getString("CAPACITY");
                String q2 = "INSERT INTO APP.VALIDMODULES2 (MODULES, OCCURENCE, \"DAY\", TIMESTART, TIMEEND, ACTIVITYTYPE, LECTURER, CAPACITY)	VALUES ('"+mod+"', "+occ+", '"+DAY+"', '"+START+"', '"+END+"', '"+ACTIVITYTYPE+"', '"+LECTURER+"', "+newcap+")";
                ps2 = con.prepareStatement(q2);
                ps2.executeUpdate();
                String q3 = "DELETE FROM APP.VALIDMODULES2 WHERE MODULES = '"+mod+"' AND OCCURENCE = "+occ+" AND \"DAY\" = '"+DAY+"' AND TIMESTART = '"+START+"' AND TIMEEND = '"+END+"' AND ACTIVITYTYPE = '"+ACTIVITYTYPE+"' AND LECTURER = '"+LECTURER+"' AND CAPACITY = "+CAP+"";
                ps3 = con.prepareStatement(q3);
                ps3.executeUpdate();
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        JOptionPane.showMessageDialog(null, "Capacity updated !");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditCapacity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditCapacity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditCapacity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditCapacity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditCapacity().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NewCapacity;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
